adlectives = [
{'adjective' : 'adorable',    'meaning' : 'used to describe someone or something that makes you love or like them'},
{'adjective' : 'adventurous', 'meaning' : 'willing to try new or difficult things'},
{'adjective' : 'aggressive',  'meaning' : 'showing anger and a willingness to attack other people'},
{'adjective' : 'agreeable',   'meaning' : 'pleasant or pleasing'},
{'adjective' : 'Agreeable',   'meaning' : 'able to be accepted by everyone / willing to do or accept something'},
{'adjective' : 'alive',       'meaning' : 'living, not dead'},
{'adjective' : 'Amused',      'meaning' : 'showing that you think something is funny'},
{'adjective' : 'annoyed',     'meaning' : 'angry'},
{'adjective' : 'annoying',    'meaning' : 'making you feel slightly angry'},
{'adjective' : 'anxious',     'meaning' : 'wanting very much for something to happen; eager'},
{'adjective' : 'arrogant',    'meaning' : 'unpleasantly proud and behaving as if you are more important than, or know more than, other people'},
{'adjective' : 'ashamed',     'meaning' : 'feeling bad because you are aware that others know that you or someone connected with you has done something wrong or embarrassing'},
{'adjective' : 'attractive',  'meaning' : 'causing interest or pleasure'},
{'adjective' : 'average',     'meaning' : 'typical and usual'},
{'adjective' : 'awful',       'meaning' : 'extremely bad or unpleasant'},
{'adjective' : 'awful',       'meaning' : 'very great or large'},
{'adjective' : 'bewildered',  'meaning' : 'confused and uncertain'},
{'adjective' : 'bloody',      'meaning' : 'used to express anger or to emphasize what you are saying in a slightly rude way / also blood stuff'},
{'adjective' : 'brainy',      'meaning' : 'intelligent, clever'},
{'adjective' : 'bright',      'meaning' : 'full of light, or shining'},
{'adjective' : 'cheerful',    'meaning' : 'happy and positive'},
{'adjective' : 'clever',      'meaning' : 'having or showing the ability to learn and understand things quickly and easily'},
{'adjective' : 'cloudy',      'meaning' : 'with clouds or not transparent'},
{'adjective' : 'clumsy',      'meaning' : 'this person often has accidents because they do not behave in a careful, controlled way'},
{'adjective' : 'concerned',   'meaning' : 'worried, involved in something or affected by it'},
]
