adjectives = [
{'adjective' : 'adorable',    'meaning' : 'used to describe someone or something that makes you love or like them', 'example' : 'He was an absolutely adorable child'},
{'adjective' : 'adventurous', 'meaning' : 'willing to try new or difficult things', 'example' : 'I\'m trying to be more adventurous with my cooking'},
{'adjective' : 'aggressive',  'meaning' : 'showing anger and a willingness to attack other people', 'example' : 'If I criticize him, he gets aggressive and starts shouting'},
{'adjective' : 'agreeable',   'meaning' : 'pleasant or pleasing', 'example' : 'We spent a most agreeable evening by the river'},
{'adjective' : 'agreeable',   'meaning' : 'able to be accepted by everyone / willing to do or accept something', 'example' : 'We need to find a compromise that is agreeable to both sides of the party'},
{'adjective' : 'alive',       'meaning' : 'living, not dead', 'example' : 'He must be 90 if he\'s still alive'},
{'adjective' : 'amused',      'meaning' : 'showing that you think something is funny', 'example' : 'She was very amused by/at your comments'},
{'adjective' : 'annoyed',     'meaning' : 'angry', 'example' : 'She was annoyed to discover that her husband had taken her car keys'},
{'adjective' : 'annoying',    'meaning' : 'making you feel slightly angry', 'example' : 'It\'s really annoying when a train is late and there\'s no explanation'},
{'adjective' : 'anxious',     'meaning' : 'wanting very much for something to happen; eager', 'example' : 'I\'ve been anxious to meet you'},
{'adjective' : 'arrogant',    'meaning' : 'unpleasantly proud and behaving as if you are more important than, or know more than, other people', 'example' : 'I found him arrogant and rude'},
{'adjective' : 'ashamed',     'meaning' : 'feeling bad because you are aware that others know that you or someone connected with you has done something wrong or embarrassing', 'example' : 'I felt deeply ashamed for my father’s impoliteness'},
{'adjective' : 'attractive',  'meaning' : 'causing interest or pleasure', 'example' : 'We need to make the club attractive to a wider range of people'},
{'adjective' : 'average',     'meaning' : 'typical and usual', 'example' : 'A student of average ability'},
{'adjective' : 'awful',       'meaning' : 'extremely bad or unpleasant', 'example' : 'What an awful thing to say!'},
{'adjective' : 'awful',       'meaning' : 'very great or large', 'example' : 'Fortunately it won\'t make an awful lot of difference if I don\'t pass the test'},
{'adjective' : 'bewildered',  'meaning' : 'confused and uncertain', 'example' : 'I came out of the movie a bit bewildered, but I enjoyed it'},
{'adjective' : 'bloody',      'meaning' : 'used to express anger or to emphasize what you are saying in a slightly rude way / also blood stuff', 'example' : 'Life would be bloody boring if nothing ever went wrong'},
{'adjective' : 'brainy',      'meaning' : 'intelligent, clever', 'example' : 'Sarah was beautiful and brainy'},
{'adjective' : 'bright',      'meaning' : 'full of light, or shining', 'example' : 'The rooms were bright and airy'},
{'adjective' : 'bumbling',    'meaning' : 'confused and showing no skill', 'example' : 'I\'ve never seen such bumbling incompetence!'},
{'adjective' : 'brisk',       'meaning' : 'quick, energetic, and active', 'example' : 'He set a brisk pace and we struggled to keep up'},
{'adjective' : 'cheerful',    'meaning' : 'happy and positive', 'example' : 'You\'re in a cheerful mood this morning'},
{'adjective' : 'clever',      'meaning' : 'having or showing the ability to learn and understand things quickly and easily', 'example' : 'Judy has never been very clever, but she tries hard'},
{'adjective' : 'cloudy',      'meaning' : 'with clouds or not transparent', 'example' : 'The beer was cloudy and dark'},
{'adjective' : 'clumsy',      'meaning' : 'this person often has accidents because they do not behave in a careful, controlled way', 'example' : 'That\'s the third glass you\'ve smashed this week - you\'re so clumsy!'},
{'adjective' : 'concerned',   'meaning' : 'worried, involved in something or affected by it', 'example' : 'Her job is something concerned with computers'},
{'adjective' : 'creepy',      'meaning' : 'strange or unnatural and making you feel frightened', 'example' : 'A creepy film'},
{'adjective' : 'crowded',     'meaning' : 'if a place is ..., it is full of people', 'example' : 'By ten o\'clock the bar was crowded'},
{'adjective' : 'defiant',     'meaning' : 'proudly refusing to obey authority', 'example' : 'The protesters blocking the entrance to the offices remained defiant this morning'},
{'adjective' : 'defiant',     'meaning' : 'not willing to accept criticism or disapproval', 'example' : 'The CEO was in a defiant mood as she entered the boardroom'},
{'adjective' : 'delightful',  'meaning' : 'very pleasant, attractive, or enjoyable', 'example' : 'Our new neighbours are delightful'},
{'adjective' : 'dizzy',       'meaning' : 'feeling as if everything is turning around, and that you are not able to balance and may fall over', 'example' : 'Going without sleep for a long time makes me feel dizzy and light-headed'},
{'adjective' : 'doubtful',    'meaning' : 'uncertain or unlikely', 'example' : 'It was doubtful (that) the money would ever be found'},
{'adjective' : 'drab',        'meaning' : 'plain and not interesting, or not bright in appearance', 'example' : 'He found London disagreeable, with its thick fog, cold drizzle, and drab food'},
{'adjective' : 'elated',      'meaning' : 'extremely happy and excited, often because something has happened or been achieved', 'example' : 'The prince was reported to be elated at/by the birth of his daughter'},
{'adjective' : 'dreary',      'meaning' : 'boring and making you feel unhappy', 'example' : 'She had spent another dreary day in the office'},
{'adjective' : 'narrow',      'meaning' : 'having a small distance from one side to the other, especially in comparison with the length', 'example' : 'The little village has very narrow streets'},
{'adjective' : 'damp',        'meaning' : 'slightly wet, especially in a way that is not pleasant or comfortable', 'example' : 'The grass is still damp'},
{'adjective' : 'grating',     'meaning' : 'a grating sound is unpleasant and annoying', 'example' : 'I turned on the car’s engine, and there was that familiar grating sound'},
{'adjective' : 'enchanting',  'meaning' : 'very pleasant or charming', 'example' : 'Belgium is an enchanting country'},
{'adjective' : 'envious',     'meaning' : 'wanting something another person has', 'example' : 'I\'m envious of people that have those big boats'},
]
